version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=wordle
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '9999:5432'